### PR TITLE
Status String datetime changed to long timestamp.

### PR DESCRIPTION
**Pull request by MichaelCh-svg**

### CODE REVIEW

**Comment by UnknownGuardian** [comment]
@jerodw what do you think

**Comment by jerodw** [comment]
Looks good to me. I just merged it.

**Comment by MichaelCh-svg** [comment]
I created a pull request for both tweeter and tweeter-client-samples, so
there should be one more location with a pull request if we want it.

 I couldn't create a pull request for tweeter-server-samples since that
isn't the default branch.

**Comment by UnknownGuardian** [comment]
@MichaelCh-svg Yeah, so for the server branch, you have to copy and paste all the changes over manually. I don't think you can cherry pick commits because the 2 branches don't share the same commit history.

**Comment by jerodw** [comment]
I don't see a pull request for the samples project. Did it already get
merged?

**Comment by MichaelCh-svg** [comment]
Matt merged it already.

**Pull request merged**
